### PR TITLE
Adding your fixes, will continue working.

### PR DESCRIPTION
**Pull request by dadziokPL**
For now I have built Lineage, but I had a ton of build errors, removed some stuff from device trees, and couldn't get it to run, try building yourself if you want, I have a manifest on my GitHub, but there are some more blobs needed, and some are not on the phone, I've gotta change some makefiles.

### CODE REVIEW

**Comment by Charles-IV** [comment]
I have already been building ;) - i think some of your manifest is wrong, so i will have a look.
I used extract files, which pulled some stuff, but not all, and then i cloned teamregulars, which had everything (i think) plus more. I then needed to copy c50-common to c50n - they are baisically clones.
Some blobs arent on my phone, which is why extact files didnt work.
Will probably create vendor repo. Have a look at teamregulars, and copy c50-common to c50n, and see what you get.

**Comment by Charles-IV** [comment]
Actually, I found that some of the files that adb said didn't exist, actually do exist on the phone, and now I've rooted, I might be able to get them.

**Comment by Charles-IV** [comment]
Booting into recovery gets more files, now to see if those still not pulled in recovery exist

**Comment by Charles-IV** [comment]
OK, it looks like they dont exist, its probably because los wants files aosp dont, which is why the guides say you need to be on los to run extract-files.sh. Oh well, lets hope and prey, and ive uploaded vendor/lge/c50n and c50-common to android_vendor_lge-c50n

**Comment by Charles-IV** [comment]
hmm, im getting this error, and i had it before, and it doesnt seem to be a missing vendor file, do you get this:
```make: *** No rule to make target '/media/charles/HDD/android/c50n-4034X-los-13/out/target/product/c50n/obj/lib/libtime_genoff.so', needed by '/media/charles/HDD/android/c50n-4034X-los-13/out/target/product/c50n/obj/SHARED_LIBRARIES/libandroid_servers_intermediates/LINKED/libandroid_servers.so'. Stop.```

**Comment by Charles-IV** [comment]
Actually, it is a vendor file, in c50-common.
We need to change the make files, i think i may have found something [here](https://forum.xda-developers.com/showpost.php?p=72278048&postcount=8)

**Comment by dadziokPL** [comment]
I checked it before, it is in the makefiles, I have no idea what's wrong

**Pull request merged**
