### PR TITLE
Add kernel configurations

### PR DESCRIPTION
**Pull request by Charles-IV**
Looking at other repos and the lg source code read me
the kernel config is changed to what the read me said.
I looked at other repos and added other lines, and modified them according to the read me, not sure if more is needed.

### CODE REVIEW

**Comment by Charles-IV** [comment]
Just seen the other branch.
Will code this pull request

**Comment by dadziokPL** [comment]
In lineage-13 everything's fine regarding the kernel, I've been compiling TWRP for now using this tree, if you want to help, then I cannot mount cache, data, and system in TWRP using this tree, I'm getting "unable to find partition size for" and "Invalid argument" errors. External SD surpisingly works fine. It's got something to do with the fstab, don't know what tho, any help would be appreciated.

**Comment by Charles-IV** [comment]
ok, i'll have a look, but tbh im not that good at this stuff

**Comment by Charles-IV** [comment]
ok, im running complete stock on mine, and tried to pull fstab.c50n. I got permission denied, but i did pull the fota.fstab ([github gist](https://gist.github.com/Charles-IV/59ed49d748b044932e1a949c2b0ad930)).
I couldn't find recovery.fsab or vold.fstab, but im searching

**Comment by Charles-IV** [comment]
and also, when i ran adb shell mount, heres the output: [github gist](https://gist.github.com/Charles-IV/aaa2d567a8610c2248cc65d2ff494a96)

**Comment by Charles-IV** [comment]
ill open a pr with what i think it should be, but im not sure

**Pull request closed without merging**
