### PR TITLE
Correct fstab

### PR DESCRIPTION
**Pull request by Charles-IV**

### CODE REVIEW

**Comment by dadziokPL** [comment]
Okay, I'll build in a moment

**Comment by dadziokPL** [comment]
OMG it works, thanks so much duuuude! Now we have our own recovery specifically for the c50n, and I'll try building Lineage 13!

**Comment by Charles-IV** [comment]
Great!
I gave up unlocking bootloader/rooting a long time ago, and I'm scared to try anything now, as it's my daily driver.
I wanted to try to do this as well, but wanted to build stock first, hence my repos, but lg have a seriously weird way of structuring their source code (no device tree, all in vendor, frameworks and external), and i couldn't do it. So I am happy to help and i have access to complete stock (always useful, i have learnt)

**Comment by Charles-IV** [comment]
Have a look at my system.prop
taken straight from my build.prop, and im thinking of removing what was there entirely, seeing as most of it is already in or commented out.

**Comment by Charles-IV** [comment]
hmm, having installed the official c50 twrp, i installed this, and this is twrp 3.0.2. I would have thought it would be 3.1.1, as that's the latest, or does the omni tree only support up to 3.0.2 on andoid-6.0 branch?

**Pull request merged**
